hook

diff --git a/.github/git-hooks/pre-commit b/.github/git-hooks/pre-commit
--- a/.github/git-hooks/pre-commit
+++ b/.github/git-hooks/pre-commit
@@ -3,25 +3,25 @@ cd "$(git rev-parse --show-toplevel)"
 ESLINT="node_modules/.bin/eslint"
 pwd
 
-if [[ ! -x "$ESLINT" ]]; then
-  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
-  exit 1
-fi
-
 STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"))
 
 if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
+failed=0
+for file in ${STAGED_FILES}; do
+  git show :$file | eslint $file
+  if [[ $? != 0 ]] ; then
+    failed=1
+  fi
+done;
+
+
 
 ESLINT_EXIT="$?"
 
-if [ $? -ne 0 ]; then
-    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
-    exit 1 # exit with failure status
-    else
-      printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
-  fi
-
-exit $?
+if [[ $failed != 0 ]] ; then
+  echo "🚫🚫🚫 ESLint failed, git commit denied!"
+  exit $failed
+fi
