Some comits

diff --git a/.github/git-hooks/pre-push b/.github/git-hooks/pre-push
--- a/.github/git-hooks/pre-push
+++ b/.github/git-hooks/pre-push
@@ -1,4 +1,8 @@
 #!/bin/bash
 
 npm run test
-echo $?
+
+if [[ $failed != 0 ]] ; then
+  echo "🚫🚫🚫 Tests failed, git push denied!"
+  exit $failed
+fi
